### ISSUE TITLE
[feat] 사용자 로그인 및 회원가입 로직 구현

### ISSUE THREAD

**Issue by RyuKwanKon** [gachon-crpyto-market/user-service#3]
## 🍀 Description

사용자 로그인 및 회원가입 로직 구현

## 🍀 Todo
- [x] user document 구현
- [x] history document 구현
- [x] 로그인 로직 구현
- [x] 회원가입 로직 구현
